-- migration.sql  (PostgreSQL; schema = app)

BEGIN;

-- Ensure target schema and search_path
CREATE SCHEMA IF NOT EXISTS app;
SET search_path = app, public;

-- --- Drop old FKs if present (from former MySQL naming) ---
ALTER TABLE IF EXISTS app."Review"  DROP CONSTRAINT IF EXISTS "Review_productId_fkey";
ALTER TABLE IF EXISTS app."Summary" DROP CONSTRAINT IF EXISTS "Summary_productId_fkey";

-- --- Drop old tables if present (camelCase) ---
DROP TABLE IF EXISTS app."Product"  CASCADE;
DROP TABLE IF EXISTS app."Review"   CASCADE;
DROP TABLE IF EXISTS app."Summary"  CASCADE;

-- --- Create new tables (snake_case) ---
CREATE TABLE app.products (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar(255) NOT NULL,
  description  text,
  price        NUMERIC(10,2) NOT NULL
);

CREATE TABLE app.reviews (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author      varchar(255) NOT NULL,
  rating      smallint NOT NULL,
  "content"   text NOT NULL,
  "createdAt" timestamptz(3) NOT NULL DEFAULT now(),
  "productId" integer NOT NULL
);

CREATE TABLE app.summaries (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId"   integer NOT NULL UNIQUE,
  "content"     text NOT NULL,
  "generatedAt" timestamptz(3) NOT NULL DEFAULT now(),
  "expiresAt"   timestamptz(3) NOT NULL
);

-- --- FKs (match your original: ON DELETE RESTRICT / ON UPDATE CASCADE) ---
ALTER TABLE app.reviews
  ADD CONSTRAINT reviews_productId_fkey
  FOREIGN KEY ("productId") REFERENCES app.products(id)
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE app.summaries
  ADD CONSTRAINT summaries_productId_fkey
  FOREIGN KEY ("productId") REFERENCES app.products(id)
  ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;
